alias gs='git status'
alias gremote='git remote'
alias grv='gr -v'
alias gb='git branch'
alias gba='gb -a'
alias gbm='gb -m'
alias gd='git diff'
alias gdhead='git diff HEAD'
alias gdc='gd --cached'
alias gpush='git push'
alias gpo='gp origin'
alias gpom='gpo master'
alias ga='git add'
alias ga.='ga .'
alias gc='git commit'
alias gcm='gc -m'
alias gpull='git pull'
alias gpr='gpull --rebase'
alias gck='git checkout'
alias gcb='gch -b'
alias gstash='git stash save'
alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gclone='git clone'
alias gpushall='git push --recurse-submodules=on-demand'
alias gresume='git stash apply'
