alias gstatus='git status'
alias gremote='git remote'
alias grv='gr -v'
alias gbranch='git branch'
alias gba='gb -a'
alias gbm='gb -m'
alias gdiff='git diff'
alias gdc='gd --cached'
alias gpush='git push'
alias gpo='gp origin'
alias gpom='gpo master'
alias gadd='git add'
alias gadd.='ga .'
alias gcommit='gc -m'
alias gpull='git pull'
alias gpr='gpull --rebase'
alias gcheckout='git checkout'
alias gcb='gch -b'
alias gstash='git stash'
alias glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gclone='git clone'
alias gpushall='git push --recurse-submodules=on-demand'
