#Hadoop CMD alias
alias hls='hadoop fs -ls '
alias hcat='hadoop fs -cat '
alias hlsr='hadoop fs -ls -R '
alias hput='hadoop fs -put '
alias hget='hadoop fs -get '
alias hmkdir='hadoop fs -mkdir -p '
alias hrm='hadoop fs -rm '
alias hcp='hadoop fs -cp '
alias hmv='hadoop fs -mv '
alias hdu='hadoop fs -du '
alias htail='hadoop fs -tail '
alias hcount='hadoop fs -count '
